package com.example.cft_test.exception;

import org.jetbrains.annotations.NotNull;

public class AlreadyExistsException extends Exception {
    public AlreadyExistsException() {
    }

    public AlreadyExistsException(String message) {
        super(message);
    }

    public AlreadyExistsException(@NotNull Class<?> objectClass, String parameter) {
        super("Object of class: " + objectClass.getCanonicalName() + " is already exists with parameter: " + parameter);
    }

    public AlreadyExistsException(String message, Throwable cause) {
        super(message, cause);
    }

    public AlreadyExistsException(Throwable cause) {
        super(cause);
    }

    public AlreadyExistsException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace) {
        super(message, cause, enableSuppression, writableStackTrace);
    }
}
